### ISSUE TITLE
does sequence order matter? 

### ISSUE THREAD

**Issue by ronpastore** [aryann/difflib#1]
Hi, not sure if i'm using this correctly, should the diff work regardless of order of the sequences? if so getting some weird output.  
# seq2 is always []string{"stove", "oven"}

difflib.Diff(seq1, seq2)
# when seq1 is ["stove", "oven"], all looks good

([]difflib.DiffRecord) (len=2 cap=2) {
 (difflib.DiffRecord)   stove,
 (difflib.DiffRecord)   oven
}
# but when reversed, diffing ["oven", "stove"], "oven" appears to be unique to both strings?

([]difflib.DiffRecord) (len=3 cap=3) {
 (difflib.DiffRecord) - oven,
 (difflib.DiffRecord)   stove,
 (difflib.DiffRecord) + oven
}

**Comment by aryann** [comment]
This is working as intended. difflib cares about order. Its main use-case is comparing files; it does this by generating the minimum number of insertions and deletions that is required to make seq1 == seq2.

You can still use difflib, though. To make it ignore order, sort both collections beforehand. However, I don't recommend doing this because there are more efficient ways of performing a diff of two collections when you don't care about order (difflib is very memory-hungry). Here are two ideas that come to mind:

1) Sort both collections, and create variables i and j for keeping track of where you are in seq1 and seq2, respectively. If seq1[i] == seq2[j], there is no difference, so increment both i and j. If seq1[i] < seq2[j], you have found an item that is in seq1 but not seq2, output it, and increment i. Do the equivalent for seq1[i] > seq2[j]. Keep doing this until you reach the end of one of the sequences. If there are still leftover items in one sequence, output those as well.

2) Use a map to keep track of the discrepancies:

```
create a map M of type string (or whatever type seq1 and seq2 contain) -> integer
for each item X in seq1:
  M[X] = (M[X] or 0) + 1
for each item X in seq2:
  M[X] = (M[X] or 0) - 1
for each item X in M:
  if M[X] == 0
    Both sequences had the same number of X, so continue
  if M[X] > 0
    X appears in seq1 M[X] time more than it does in seq2
  else
    X appears in seq2 |M[X]| times more than it does in seq1
```

Let me know if this helps, and thanks for considering difflib!

**Comment by ronpastore** [comment]
ah yes this helps a bunch! sorting beforehand appears to work. my use case is mostly small slices so i think it should be all good. thanks!
